version: '3'

services:
  api:
    build: ./server
    volumes:
      - ./server:/app
    networks:
      - api-db
      - default
    command: >
      sh -c "npm rebuild bcrypt --build-from-source && npx prisma migrate dev --name init && npm start"
    depends_on:
      - db
    env_file:
      - ./server/.env
  
  db:
    image: postgres:latest
    networks:
      - api-db
    ports:
      - "5432:5432"
    env_file:
      - ./server/.env
  
  # client:
  #   build: ./client
  #   volumes:
  #     - ./client:/app
  #   networks:
  #     - default
  #   command: npm start
  #   depends_on:
  #     - api
  #   env_file:
  #     - ./client/.env
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    networks:
      - default
    depends_on:
      - api

networks:
  api-db:
    driver: bridge
  
  default:
    driver: bridge